<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $title
 * @property string $content
 * @property integer $section_id
 * @property integer $sort_order
 * @property Section $Section
 * @property Doctrine_Collection $Photos
 * 
 * @method varchar             getTitle()      Returns the current record's "title" value
 * @method string              getContent()    Returns the current record's "content" value
 * @method integer             getSectionId()  Returns the current record's "section_id" value
 * @method integer             getSortOrder()  Returns the current record's "sort_order" value
 * @method Section             getSection()    Returns the current record's "Section" value
 * @method Doctrine_Collection getPhotos()     Returns the current record's "Photos" collection
 * @method Category            setTitle()      Sets the current record's "title" value
 * @method Category            setContent()    Sets the current record's "content" value
 * @method Category            setSectionId()  Sets the current record's "section_id" value
 * @method Category            setSortOrder()  Sets the current record's "sort_order" value
 * @method Category            setSection()    Sets the current record's "Section" value
 * @method Category            setPhotos()     Sets the current record's "Photos" collection
 * 
 * @package    PhotoSite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('title', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('content', 'string', 3000, array(
             'type' => 'string',
             'length' => 3000,
             ));
        $this->hasColumn('section_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('sort_order', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Section', array(
             'local' => 'section_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('Photo as Photos', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'content',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'title',
             ),
             'canUpdate' => true,
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}