<?php

/**
 * BaseSection
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property varchar $title
 * @property boolean $online
 * @property integer $sort_order
 * @property Doctrine_Collection $Categories
 * 
 * @method varchar             getTitle()      Returns the current record's "title" value
 * @method boolean             getOnline()     Returns the current record's "online" value
 * @method integer             getSortOrder()  Returns the current record's "sort_order" value
 * @method Doctrine_Collection getCategories() Returns the current record's "Categories" collection
 * @method Section             setTitle()      Sets the current record's "title" value
 * @method Section             setOnline()     Sets the current record's "online" value
 * @method Section             setSortOrder()  Sets the current record's "sort_order" value
 * @method Section             setCategories() Sets the current record's "Categories" collection
 * 
 * @package    PhotoSite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSection extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('section');
        $this->hasColumn('title', 'varchar', 255, array(
             'type' => 'varchar',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('online', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('sort_order', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as Categories', array(
             'local' => 'id',
             'foreign' => 'section_id'));

        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             ));
        $sluggable1 = new Doctrine_Template_Sluggable(array(
             'fields' => 
             array(
              0 => 'title',
             ),
             'uniqueBy' => 
             array(
              0 => 'lang',
              1 => 'title',
             ),
             'canUpdate' => true,
             ));
        $i18n0->addChild($sluggable1);
        $this->actAs($i18n0);
    }
}