<?php

/**
 * Category
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhotoSite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Category extends BaseCategory
{
    public function getSectionSlug()
    {
        return $this->getSection()->getSlug();
    }

    public function getFirstPhoto()
    {
        $q = Doctrine::getTable('Photo')->createQuery('p');
        $q->leftJoin('p.Category c');
        $q->where('c.id = ?', $this->getId());
        $q->orderBy('p.sort_order ASC');

        $photos = $q->execute();

        return $photos->getFirst();
    }

    public function getPhotos()
    {
        $q = Doctrine::getTable('Photo')->createQuery('p');
        $q->select('p.id');
        $q->leftJoin('p.Category c');
        $q->where('c.id = ?', $this->getId());
        $q->orderBy('p.sort_order ASC');

        return $q->execute();
    }
}
