<?php

/**
 * Photo
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    PhotoSite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Photo extends BasePhoto {
    public function generateImageFilename(sfValidatedFile $validatedFile) {
        $filename = str_replace($validatedFile->getOriginalExtension(), '', $validatedFile->getOriginalName());
//        var_dump($filename);
//        exit;
        return PhotoSite::slugify($filename).$validatedFile->getExtension($validatedFile->getOriginalExtension());
    }

    public function  getSection() {
        return $this->getCategory()->getSection();
    }
}
