<?php

/**
 * Section
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PhotoSite
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Section extends BaseSection
{
    public function getCategories()
    {
        $q = Doctrine::getTable('Category')->createQuery('c');
        $q->select('c.id');
        $q->leftJoin('c.Section s');
        $q->where('s.id = ?', $this->getId());
        $q->orderBy('c.sort_order ASC');
        return $q->execute();
    }
}
