generator:
  class: sfDoctrineGenerator
  param:
    model_class:           category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          category
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=title, section]
        sort: [sort_order, asc]
      filter:
        display: [section_id]
      form:    ~
      edit:    ~
      new:     ~
