generator:
  class: sfDoctrineGenerator
  param:
    model_class:           photo
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          photo
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [=title, category, section]
        sort: [sort_order]
      filter:
        display: [title, caption, category_id]
      form:    ~
      edit:    ~
      new:     ~
