<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addsection extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('section', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => 8,
              'autoincrement' => true,
              'primary' => true,
             ),
             'online' => 
             array(
              'type' => 'boolean',
              'length' => 25,
             ),
             'sort_order' => 
             array(
              'type' => 'integer',
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('section');
    }
}